### ISSUE TITLE
서비스에서 스크롤을 다 내렸을 때 GoAppCard 컴포넌트 띄우기

### ISSUE THREAD

**Issue by kingyong9169** [Nexters/daily-phrase-web#19]
## 설명
서비스에서 스크롤을 다 내렸을 때 GoAppCard 컴포넌트 띄우기

## 할 일

- [ ] 스크롤 로직

**Comment by bepyan** [comment]
GoAppCard 컴포넌트는 페이지 바닥에 위치해서 스크롤 내렸을 때 보여줄 필요는 없지 않나?

**Comment by kingyong9169** [comment]
@bepyan 아하 페이지 다 내리면 보여주면 되는구나~ 그렇게 하면 되겄다
