### ISSUE TITLE
서비스, 백오피스 폰트 세팅

### ISSUE THREAD

**Issue by kingyong9169** [Nexters/daily-phrase-web#21]
## 할 일

- [x] 서비스 pretendard 적용
- [ ] 백오피스 pretendard 적용

참고로 web은 babel을 쓰고 있어서 next/font 사용을 못해!

**Comment by bepyan** [comment]
https://github.com/Nexters/daily-phrase-web/pull/11#discussion_r1463454688
CSS `@import` 방식이 아닌 `<link>` 태그 방식으로 css를 불러오는 것이 cdn css 파일을 더 일찍 받아 올 수 있다.

추가로 체크해야 할 것
- [ ] nextjs app directory에서는 이를 어떻게 적용할 수 있는지 조사 필요.
